<?php
return  [
    'timezone' => [
        'Africa/Algiers' => 'Algeria (+01:00)',
        'Africa/Gaborone' => 'Botswana (+02:00)',
        'Africa/Douala' => 'Cameroon (+01:00)',
        'Africa/Bangui' => 'Central African Republic (+01:00)',
        'Africa/Ndjamena' => 'Chad (+01:00)',
        'Africa/Kinshasa' => 'Democratic Republic of the Congo (+01:00)',
        'Africa/Djibouti' => 'Djibouti (+03:00)',
        'Africa/Cairo' => 'Egypt (+02:00)',
        'Africa/Malabo' => 'Equatorial Guinea (+01:00)',
        'Africa/Asmara' => 'Eritrea (+03:00)',
        'Africa/Addis_Ababa' => 'Ethiopia (+03:00)',
        'Africa/Libreville' => 'Gabon (+01:00)',
        'Africa/Banjul' => 'Gambia (+00:00)',
        'Africa/Accra' => 'Ghana (+00:00)',
        'Africa/Conakry' => 'Guinea (+00:00)',
        'Africa/Bissau' => 'Guinea-Bissau (+00:00)',
        'Africa/Abidjan' => 'Ivory Coast (+00:00)',
        'Africa/Nairobi' => 'Kenya (+03:00)',
        'Africa/Maseru' => 'Lesotho (+02:00)',
        'Africa/Monrovia' => 'Liberia (+00:00)',
        'Africa/Tripoli' => 'Libya (+02:00)',
        'Africa/Blantyre' => 'Malawi (+02:00)',
        'Africa/Bamako' => 'Mali (+00:00)',
        'Africa/Nouakchott' => 'Mauritania (+00:00)',
        'Africa/Casablanca' => 'Morocco (+01:00)',
        'Africa/Maputo' => 'Mozambique (+02:00)',
        'Africa/Windhoek' => 'Namibia (+01:00)',
        'Africa/Niamey' => 'Niger (+01:00)',
        'Africa/Lagos' => 'Nigeria (+01:00)',
        'Africa/Brazzaville' => 'Republic of the Congo (+01:00)',
        'Africa/Kigali' => 'Rwanda (+02:00)',
        'Africa/Sao_Tome' => 'Sao Tome and Principe (+00:00)',
        'Africa/Dakar' => 'Senegal (+00:00)',
        'Africa/Freetown' => 'Sierra Leone (+00:00)',
        'Africa/Mogadishu' => 'Somalia (+03:00)',
        'Africa/Johannesburg' => 'South Africa (+02:00)',
        'Africa/Juba' => 'South Sudan (+03:00)',
        'Africa/Khartoum' => 'Sudan (+03:00)',
        'Africa/Mbabane' => 'Swaziland (+02:00)',
        'Africa/Dar_es_Salaam' => 'Tanzania (+03:00)',
        'Africa/Lome' => 'Togo (+00:00)',
        'Africa/Tunis' => 'Tunisia (+01:00)',
        'Africa/Kampala' => 'Uganda (+03:00)',
        'Africa/El_Aaiun' => 'Western Sahara (+00:00)',
        'Africa/Lusaka' => 'Zambia (+02:00)',
        'Africa/Harare' => 'Zimbabwe (+02:00)',
        'America/Nassau' => 'Bahamas (-04:00)',
        'America/Belize' => 'Belize (-06:00)',
        'America/Noronha' => 'Brazil (-02:00)',
        'America/Tortola' => 'British Virgin Islands (-04:00)',
        'America/St_Johns' => 'Canada (-02:30)',
        'America/Cayman' => 'Cayman Islands (-05:00)',
        'America/Santiago' => 'Chile (-04:00)',
        'America/Bogota' => 'Colombia (-05:00)',
        'America/Costa_Rica' => 'Costa Rica (-06:00)',
        'America/Havana' => 'Cuba (-04:00)',
        'America/Curacao' => 'Curaçao (-04:00)',
        'America/Dominica' => 'Dominica (-04:00)',
        'America/Santo_Domingo' => 'Dominican Republic (-04:00)',
        'America/Guayaquil' => 'Ecuador (-05:00)',
        'America/El_Salvador' => 'El Salvador (-06:00)',
        'America/Cayenne' => 'French Guiana (-03:00)',
        'America/Godthab' => 'Greenland (-02:00)',
        'America/Grenada' => 'Grenada (-04:00)',
        'America/Guadeloupe' => 'Guadeloupe (-04:00)',
        'America/Guatemala' => 'Guatemala (-06:00)',
        'America/Guyana' => 'Guyana (-04:00)',
        'America/Port-au-Prince' => 'Haiti (-05:00)',
        'America/Tegucigalpa' => 'Honduras (-06:00)',
        'America/Jamaica' => 'Jamaica (-05:00)',
        'America/Martinique' => 'Martinique (-04:00)',
        'America/Mexico_City' => 'Mexico (-05:00)',
        'America/Montserrat' => 'Montserrat (-04:00)',
        'America/Managua' => 'Nicaragua (-06:00)',
        'America/Panama' => 'Panama (-05:00)',
        'America/Asuncion' => 'Paraguay (-04:00)',
        'America/Lima' => 'Peru (-05:00)',
        'America/Puerto_Rico' => 'Puerto Rico (-04:00)',
        'America/St_Kitts' => 'Saint Kitts and Nevis (-04:00)',
        'America/St_Lucia' => 'Saint Lucia (-04:00)',
        'America/Marigot' => 'Saint Martin (-04:00)',
        'America/Miquelon' => 'Saint Pierre and Miquelon (-02:00)',
        'America/St_Vincent' => 'Saint Vincent and the Grenadines (-04:00)',
        'America/Lower_Princes' => 'Sint Maarten (-04:00)',
        'America/Paramaribo' => 'Suriname (-03:00)',
        'America/Port_of_Spain' => 'Trinidad and Tobago (-04:00)',
        'America/Grand_Turk' => 'Turks and Caicos Islands (-04:00)',
        'America/St_Thomas' => 'U.S. Virgin Islands (-04:00)',
        'America/New_York' => 'United States (-04:00)',
        'America/Montevideo' => 'Uruguay (-03:00)',
        'Europe/Vatican' => 'Vatican (+02:00)',
        'America/Caracas' => 'Venezuela (-04:30)',
        'Asia/Thimphu' => 'Bhutan (+06:00)',
        'Asia/Phnom_Penh' => 'Cambodia (+07:00)',
        'Asia/Shanghai' => 'China (+08:00)',
        'Asia/Nicosia' => 'Cyprus (+03:00)',
        'Asia/Dili' => 'East Timor (+09:00)',
        'Asia/Tbilisi' => 'Georgia (+04:00)',
        'Asia/Hong_Kong' => 'Hong Kong (+08:00)',
        'Asia/Kolkata' => 'India (+05:30)',
        'Asia/Jakarta' => 'Indonesia (+07:00)',
        'Asia/Tehran' => 'Iran (+04:30)',
        'Asia/Baghdad' => 'Iraq (+03:00)',
        'Asia/Jerusalem' => 'Israel (+03:00)',
        'Asia/Tokyo' => 'Japan (+09:00)',
        'Asia/Amman' => 'Jordan (+03:00)',
        'Asia/Almaty' => 'Kazakhstan (+06:00)',
        'Asia/Kuwait' => 'Kuwait (+03:00)',
        'Asia/Bishkek' => 'Kyrgyzstan (+06:00)',
        'Asia/Vientiane' => 'Laos (+07:00)',
        'Asia/Beirut' => 'Lebanon (+03:00)',
        'Asia/Macau' => 'Macao (+08:00)',
        'Asia/Kuala_Lumpur' => 'Malaysia (+08:00)',
        'Asia/Ulaanbaatar' => 'Mongolia (+08:00)',
        'Asia/Rangoon' => 'Myanmar (+06:30)',
        'Asia/Kathmandu' => 'Nepal (+05:45)',
        'Asia/Pyongyang' => 'North Korea (+09:00)',
        'Asia/Muscat' => 'Oman (+04:00)',
        'Asia/Karachi' => 'Pakistan (+05:00)',
        'Asia/Gaza' => 'Palestinian Territory (+02:00)',
        'Asia/Manila' => 'Philippines (+08:00)',
        'Asia/Qatar' => 'Qatar (+03:00)',
        'Asia/Riyadh' => 'Saudi Arabia (+03:00)',
        'Asia/Singapore' => 'Singapore (+08:00)',
        'Asia/Seoul' => 'South Korea (+09:00)',
        'Asia/Colombo' => 'Sri Lanka (+05:30)',
        'Asia/Damascus' => 'Syria (+03:00)',
        'Asia/Taipei' => 'Taiwan (+08:00)',
        'Asia/Dushanbe' => 'Tajikistan (+05:00)',
        'Asia/Bangkok' => 'Thailand (+07:00)',
        'Asia/Ashgabat' => 'Turkmenistan (+05:00)',
        'Asia/Samarkand' => 'Uzbekistan (+05:00)',
        'Asia/Ho_Chi_Minh' => 'Vietnam (+07:00)',
        'Asia/Aden' => 'Yemen (+03:00)',
        'Atlantic/Cape_Verde' => 'Cape Verde (-01:00)',
        'Atlantic/Stanley' => 'Falkland Islands (-03:00)',
        'Atlantic/Faroe' => 'Faroe Islands (+01:00)',
        'Atlantic/Reykjavik' => 'Iceland (+00:00)',
        'Atlantic/St_Helena' => 'Saint Helena (+00:00)',
        'Atlantic/South_Georgia' => 'South Georgia and the South Sandwich Islands (-02:00)',
        'Europe/Minsk' => 'Belarus (+03:00)',
        'Europe/Zagreb' => 'Croatia (+02:00)',
        'Europe/Prague' => 'Czech Republic (+02:00)',
        'Europe/Copenhagen' => 'Denmark (+02:00)',
        'Europe/Tallinn' => 'Estonia (+03:00)',
        'Europe/Helsinki' => 'Finland (+03:00)',
        'Europe/Paris' => 'France (+02:00)',
        'Europe/Berlin' => 'Germany (+02:00)',
        'Europe/Gibraltar' => 'Gibraltar (+02:00)',
        'Europe/Athens' => 'Greece (+03:00)',
        'Europe/Guernsey' => 'Guernsey (+01:00)',
        'Europe/Budapest' => 'Hungary (+02:00)',
        'Europe/Dublin' => 'Ireland (+01:00)',
        'Europe/Isle_of_Man' => 'Isle of Man (+01:00)',
        'Europe/Rome' => 'Italy (+02:00)',
        'Europe/Jersey' => 'Jersey (+01:00)',
        'Europe/Riga' => 'Latvia (+03:00)',
        'Europe/Vaduz' => 'Liechtenstein (+02:00)',
        'Europe/Vilnius' => 'Lithuania (+03:00)',
        'Europe/Luxembourg' => 'Luxembourg (+02:00)',
        'Europe/Skopje' => 'Macedonia (+02:00)',
        'Europe/Malta' => 'Malta (+02:00)',
        'Europe/Chisinau' => 'Moldova (+03:00)',
        'Europe/Monaco' => 'Monaco (+02:00)',
        'Europe/Podgorica' => 'Montenegro (+02:00)',
        'Europe/Amsterdam' => 'Netherlands (+02:00)',
        'Europe/Oslo' => 'Norway (+02:00)',
        'Europe/Warsaw' => 'Poland (+02:00)',
        'Europe/Lisbon' => 'Portugal (+01:00)',
        'Europe/Bucharest' => 'Romania (+03:00)',
        'Europe/Kaliningrad' => 'Russia (+03:00)',
        'Europe/San_Marino' => 'San Marino (+02:00)',
        'Europe/Belgrade' => 'Serbia (+02:00)',
        'Europe/Bratislava' => 'Slovakia (+02:00)',
        'Europe/Ljubljana' => 'Slovenia (+02:00)',
        'Europe/Madrid' => 'Spain (+02:00)',
        'Europe/Stockholm' => 'Sweden (+02:00)',
        'Europe/Zurich' => 'Switzerland (+02:00)',
        'Europe/Istanbul' => 'Turkey (+03:00)',
        'Europe/Kiev' => 'Ukraine (+03:00)',
        'Europe/London' => 'United Kingdom (+01:00)',
        'Indian/Chagos' => 'British Indian Ocean Territory (+06:00)',
        'Indian/Christmas' => 'Christmas Island (+07:00)',
        'Indian/Cocos' => 'Cocos Islands (+06:30)',
        'Indian/Comoro' => 'Comoros (+03:00)',
        'Indian/Kerguelen' => 'French Southern Territories (+05:00)',
        'Indian/Antananarivo' => 'Madagascar (+03:00)',
        'Indian/Maldives' => 'Maldives (+05:00)',
        'Indian/Mauritius' => 'Mauritius (+04:00)',
        'Indian/Mayotte' => 'Mayotte (+03:00)',
        'Indian/Reunion' => 'Reunion (+04:00)',
        'Indian/Mahe' => 'Seychelles (+04:00)',
        'Pacific/Rarotonga' => 'Cook Islands (-10:00)',
        'Pacific/Fiji' => 'Fiji (+12:00)',
        'Pacific/Tahiti' => 'French Polynesia (-10:00)',
        'Pacific/Guam' => 'Guam (+10:00)',
        'Pacific/Tarawa' => 'Kiribati (+12:00)',
        'Pacific/Majuro' => 'Marshall Islands (+12:00)',
        'Pacific/Chuuk' => 'Micronesia (+10:00)',
        'Pacific/Nauru' => 'Nauru (+12:00)',
        'Pacific/Noumea' => 'New Caledonia (+11:00)',
        'Pacific/Auckland' => 'New Zealand (+12:00)',
        'Pacific/Niue' => 'Niue (-11:00)',
        'Pacific/Norfolk' => 'Norfolk Island (+11:30)',
        'Pacific/Saipan' => 'Northern Mariana Islands (+10:00)',
        'Pacific/Palau' => 'Palau (+09:00)',
        'Pacific/Port_Moresby' => 'Papua New Guinea (+10:00)',
        'Pacific/Pitcairn' => 'Pitcairn (-08:00)',
        'Pacific/Apia' => 'Samoa (+13:00)',
        'Pacific/Guadalcanal' => 'Solomon Islands (+11:00)',
        'Pacific/Fakaofo' => 'Tokelau (+14:00)',
        'Pacific/Tongatapu' => 'Tonga (+13:00)',
        'Pacific/Funafuti' => 'Tuvalu (+12:00)',
        'Pacific/Johnston' => 'United States Minor Outlying Islands (-10:00)',
        'Pacific/Efate' => 'Vanuatu (+11:00)',
        'Pacific/Wallis' => 'Wallis and Futuna (+12:00)',
        'UTC' => 'UTC',
    ],
    'nationality' => array(
        "Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cape Verde",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Colombi",
        "Comoros",
        "Congo (Brazzaville)",
        "Congo",
        "Costa Rica",
        "Cote d'Ivoire",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "East Timor (Timor Timur)",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "Fiji",
        "Finland",
        "France",
        "Gabon",
        "Gambia, The",
        "Georgia",
        "Germany",
        "Ghana",
        "Greece",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Honduras",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Korea, North",
        "Korea, South",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macedonia",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Mauritania",
        "Mauritius",
        "Mexico",
        "Micronesia",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Qatar",
        "Romania",
        "Russia",
        "Rwanda",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia and Montenegro",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Swaziland",
        "Sweden",
        "Switzerland",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Togo",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Vatican City",
        "Venezuela",
        "Vietnam",
        "Yemen",
        "Zambia",
        "Zimbabwe"
    ),
    'dial_code' =>  [
        '44' => 'UK (+44)',
        '1' => 'USA (+1)',
        '213' => 'Algeria (+213)',
        '376' => 'Andorra (+376)',
        '244' => 'Angola (+244)',
        '1264' => 'Anguilla (+1264)',
        '1268' => 'Antigua & Barbuda (+1268)',
        '54' => 'Argentina (+54)',
        '374' => 'Armenia (+374)',
        '297' => 'Aruba (+297)',
        '61' => 'Australia (+61)',
        '43' => 'Austria (+43)',
        '994' => 'Azerbaijan (+994)',
        '1242' => 'Bahamas (+1242)',
        '973' => 'Bahrain (+973)',
        '880' => 'Bangladesh (+880)',
        '1246' => 'Barbados (+1246)',
        '375' => 'Belarus (+375)',
        '32' => 'Belgium (+32)',
        '501' => 'Belize (+501)',
        '229' => 'Benin (+229)',
        '1441' => 'Bermuda (+1441)',
        '975' => 'Bhutan (+975)',
        '591' => 'Bolivia (+591)',
        '387' => 'Bosnia Herzegovina (+387)',
        '267' => 'Botswana (+267)',
        '55' => 'Brazil (+55)',
        '673' => 'Brunei (+673)',
        '359' => 'Bulgaria (+359)',
        '226' => 'Burkina Faso (+226)',
        '257' => 'Burundi (+257)',
        '855' => 'Cambodia (+855)',
        '237' => 'Cameroon (+237)',
        '1' => 'Canada (+1)',
        '238' => 'Cape Verde Islands (+238)',
        '1345' => 'Cayman Islands (+1345)',
        '236' => 'Central African Republic (+236)',
        '56' => 'Chile (+56)',
        '86' => 'China (+86)',
        '57' => 'Colombia (+57)',
        '269' => 'Comoros (+269)',
        '242' => 'Congo (+242)',
        '682' => 'Cook Islands (+682)',
        '506' => 'Costa Rica (+506)',
        '385' => 'Croatia (+385)',
        '53' => 'Cuba (+53)',
        '90392' => 'Cyprus North (+90392)',
        '357' => 'Cyprus South (+357)',
        '42' => 'Czech Republic (+42)',
        '45' => 'Denmark (+45)',
        '253' => 'Djibouti (+253)',
        '1809' => 'Dominica (+1809)',
        '1809' => 'Dominican Republic (+1809)',
        '593' => 'Ecuador (+593)',
        '20' => 'Egypt (+20)',
        '503' => 'El Salvador (+503)',
        '240' => 'Equatorial Guinea (+240)',
        '291' => 'Eritrea (+291)',
        '372' => 'Estonia (+372)',
        '251' => 'Ethiopia (+251)',
        '500' => 'Falkland Islands (+500)',
        '298' => 'Faroe Islands (+298)',
        '679' => 'Fiji (+679)',
        '358' => 'Finland (+358)',
        '33' => 'France (+33)',
        '594' => 'French Guiana (+594)',
        '689' => 'French Polynesia (+689)',
        '241' => 'Gabon (+241)',
        '220' => 'Gambia (+220)',
        '7880' => 'Georgia (+7880)',
        '49' => 'Germany (+49)',
        '233' => 'Ghana (+233)',
        '350' => 'Gibraltar (+350)',
        '30' => 'Greece (+30)',
        '299' => 'Greenland (+299)',
        '1473' => 'Grenada (+1473)',
        '590' => 'Guadeloupe (+590)',
        '671' => 'Guam (+671)',
        '502' => 'Guatemala (+502)',
        '224' => 'Guinea (+224)',
        '245' => 'Guinea - Bissau (+245)',
        '592' => 'Guyana (+592)',
        '509' => 'Haiti (+509)',
        '504' => 'Honduras (+504)',
        '852' => 'Hong Kong (+852)',
        '36' => 'Hungary (+36)',
        '354' => 'Iceland (+354)',
        '91' => 'India (+91)',
        '62' => 'Indonesia (+62)',
        '98' => 'Iran (+98)',
        '964' => 'Iraq (+964)',
        '353' => 'Ireland (+353)',
        '972' => 'Israel (+972)',
        '39' => 'Italy (+39)',
        '1876' => 'Jamaica (+1876)',
        '81' => 'Japan (+81)',
        '962' => 'Jordan (+962)',
        '7' => 'Kazakhstan (+7)',
        '254' => 'Kenya (+254)',
        '686' => 'Kiribati (+686)',
        '850' => 'Korea North (+850)',
        '82' => 'Korea South (+82)',
        '965' => 'Kuwait (+965)',
        '996' => 'Kyrgyzstan (+996)',
        '856' => 'Laos (+856)',
        '371' => 'Latvia (+371)',
        '961' => 'Lebanon (+961)',
        '266' => 'Lesotho (+266)',
        '231' => 'Liberia (+231)',
        '218' => 'Libya (+218)',
        '417' => 'Liechtenstein (+417)',
        '370' => 'Lithuania (+370)',
        '352' => 'Luxembourg (+352)',
        '853' => 'Macao (+853)',
        '389' => 'Macedonia (+389)',
        '261' => 'Madagascar (+261)',
        '265' => 'Malawi (+265)',
        '60' => 'Malaysia (+60)',
        '960' => 'Maldives (+960)',
        '223' => 'Mali (+223)',
        '356' => 'Malta (+356)',
        '692' => 'Marshall Islands (+692)',
        '596' => 'Martinique (+596)',
        '222' => 'Mauritania (+222)',
        '269' => 'Mayotte (+269)',
        '52' => 'Mexico (+52)',
        '691' => 'Micronesia (+691)',
        '373' => 'Moldova (+373)',
        '377' => 'Monaco (+377)',
        '976' => 'Mongolia (+976)',
        '1664' => 'Montserrat (+1664)',
        '212' => 'Morocco (+212)',
        '258' => 'Mozambique (+258)',
        '95' => 'Myanmar (+95)',
        '264' => 'Namibia (+264)',
        '674' => 'Nauru (+674)',
        '977' => 'Nepal (+977)',
        '31' => 'Netherlands (+31)',
        '687' => 'New Caledonia (+687)',
        '64' => 'New Zealand (+64)',
        '505' => 'Nicaragua (+505)',
        '227' => 'Niger (+227)',
        '234' => 'Nigeria (+234)',
        '683' => 'Niue (+683)',
        '672' => 'Norfolk Islands (+672)',
        '670' => 'Northern Marianas (+670)',
        '47' => 'Norway (+47)',
        '968' => 'Oman (+968)',
        '680' => 'Palau (+680)',
        '507' => 'Panama (+507)',
        '675' => 'Papua New Guinea (+675)',
        '595' => 'Paraguay (+595)',
        '51' => 'Peru (+51)',
        '63' => 'Philippines (+63)',
        '48' => 'Poland (+48)',
        '351' => 'Portugal (+351)',
        '1787' => 'Puerto Rico (+1787)',
        '974' => 'Qatar (+974)',
        '262' => 'Reunion (+262)',
        '40' => 'Romania (+40)',
        '7' => 'Russia (+7)',
        '250' => 'Rwanda (+250)',
        '378' => 'San Marino (+378)',
        '239' => 'Sao Tome & Principe (+239)',
        '966' => 'Saudi Arabia (+966)',
        '221' => 'Senegal (+221)',
        '381' => 'Serbia (+381)',
        '248' => 'Seychelles (+248)',
        '232' => 'Sierra Leone (+232)',
        '65' => 'Singapore (+65)',
        '421' => 'Slovak Republic (+421)',
        '386' => 'Slovenia (+386)',
        '677' => 'Solomon Islands (+677)',
        '252' => 'Somalia (+252)',
        '27' => 'South Africa (+27)',
        '34' => 'Spain (+34)',
        '94' => 'Sri Lanka (+94)',
        '290' => 'St. Helena (+290)',
        '1869' => 'St. Kitts (+1869)',
        '1758' => 'St. Lucia (+1758)',
        '249' => 'Sudan (+249)',
        '597' => 'Suriname (+597)',
        '268' => 'Swaziland (+268)',
        '46' => 'Sweden (+46)',
        '41' => 'Switzerland (+41)',
        '963' => 'Syria (+963)',
        '886' => 'Taiwan (+886)',
        '7' => 'Tajikstan (+7)',
        '66' => 'Thailand (+66)',
        '228' => 'Togo (+228)',
        '676' => 'Tonga (+676)',
        '1868' => 'Trinidad & Tobago (+1868)',
        '216' => 'Tunisia (+216)',
        '90' => 'Turkey (+90)',
        '7' => 'Turkmenistan (+7)',
        '993' => 'Turkmenistan (+993)',
        '1649' => 'Turks & Caicos Islands (+1649)',
        '688' => 'Tuvalu (+688)',
        '256' => 'Uganda (+256)',
        '380' => 'Ukraine (+380)',
        '971' => 'United Arab Emirates (+971)',
        '598' => 'Uruguay (+598)',
        '7' => 'Uzbekistan (+7)',
        '678' => 'Vanuatu (+678)',
        '379' => 'Vatican City (+379)',
        '58' => 'Venezuela (+58)',
        '84' => 'Vietnam (+84)',
        '84' => 'Virgin Islands - British (+1284)',
        '84' => 'Virgin Islands - US (+1340)',
        '681' => 'Wallis & Futuna (+681)',
        '969' => 'Yemen (North)(+969)',
        '967' => 'Yemen (South)(+967)',
        '260' => 'Zambia (+260)',
        '263' => 'Zimbabwe (+263)',
    ],
    'currency' => array(
        array("name" => "Afghan Afghani", "code" => "AFA", "symbol" => "؋"),
        array("name" => "Albanian Lek", "code" => "ALL", "symbol" => "Lek"),
        array("name" => "Algerian Dinar", "code" => "DZD", "symbol" => "دج"),
        array("name" => "Angolan Kwanza", "code" => "AOA", "symbol" => "Kz"),
        array("name" => "Argentine Peso", "code" => "ARS", "symbol" => "$"),
        array("name" => "Armenian Dram", "code" => "AMD", "symbol" => "֏"),
        array("name" => "Aruban Florin", "code" => "AWG", "symbol" => "ƒ"),
        array("name" => "Australian Dollar", "code" => "AUD", "symbol" => "$"),
        array("name" => "Azerbaijani Manat", "code" => "AZN", "symbol" => "m"),
        array("name" => "Bahamian Dollar", "code" => "BSD", "symbol" => "B$"),
        array("name" => "Bahraini Dinar", "code" => "BHD", "symbol" => ".د.ب"),
        array("name" => "Bangladeshi Taka", "code" => "BDT", "symbol" => "৳"),
        array("name" => "Barbadian Dollar", "code" => "BBD", "symbol" => "Bds$"),
        array("name" => "Belarusian Ruble", "code" => "BYR", "symbol" => "Br"),
        array("name" => "Belgian Franc", "code" => "BEF", "symbol" => "fr"),
        array("name" => "Belize Dollar", "code" => "BZD", "symbol" => "$"),
        array("name" => "Bermudan Dollar", "code" => "BMD", "symbol" => "$"),
        array("name" => "Bhutanese Ngultrum", "code" => "BTN", "symbol" => "Nu."),
        array("name" => "Bitcoin", "code" => "BTC", "symbol" => "฿"),
        array("name" => "Bolivian Boliviano", "code" => "BOB", "symbol" => "Bs."),
        array("name" => "Bosnia-Herzegovina Convertible Mark", "code" => "BAM", "symbol" => "KM"),
        array("name" => "Botswanan Pula", "code" => "BWP", "symbol" => "P"),
        array("name" => "Brazilian Real", "code" => "BRL", "symbol" => "R$"),
        array("name" => "British Pound Sterling", "code" => "GBP", "symbol" => "£"),
        array("name" => "Brunei Dollar", "code" => "BND", "symbol" => "B$"),
        array("name" => "Bulgarian Lev", "code" => "BGN", "symbol" => "Лв."),
        array("name" => "Burundian Franc", "code" => "BIF", "symbol" => "FBu"),
        array("name" => "Cambodian Riel", "code" => "KHR", "symbol" => "KHR"),
        array("name" => "Canadian Dollar", "code" => "CAD", "symbol" => "$"),
        array("name" => "Cape Verdean Escudo", "code" => "CVE", "symbol" => "$"),
        array("name" => "Cayman Islands Dollar", "code" => "KYD", "symbol" => "$"),
        array("name" => "CFA Franc BCEAO", "code" => "XOF", "symbol" => "CFA"),
        array("name" => "CFA Franc BEAC", "code" => "XAF", "symbol" => "FCFA"),
        array("name" => "CFP Franc", "code" => "XPF", "symbol" => "₣"),
        array("name" => "Chilean Peso", "code" => "CLP", "symbol" => "$"),
        array("name" => "Chilean Unit of Account", "code" => "CLF", "symbol" => "CLF"),
        array("name" => "Chinese Yuan", "code" => "CNY", "symbol" => "¥"),
        array("name" => "Colombian Peso", "code" => "COP", "symbol" => "$"),
        array("name" => "Comorian Franc", "code" => "KMF", "symbol" => "CF"),
        array("name" => "Congolese Franc", "code" => "CDF", "symbol" => "FC"),
        array("name" => "Costa Rican Colón", "code" => "CRC", "symbol" => "₡"),
        array("name" => "Croatian Kuna", "code" => "HRK", "symbol" => "kn"),
        array("name" => "Cuban Convertible Peso", "code" => "CUC", "symbol" => "$, CUC"),
        array("name" => "Czech Republic Koruna", "code" => "CZK", "symbol" => "Kč"),
        array("name" => "Danish Krone", "code" => "DKK", "symbol" => "Kr."),
        array("name" => "Djiboutian Franc", "code" => "DJF", "symbol" => "Fdj"),
        array("name" => "Dominican Peso", "code" => "DOP", "symbol" => "$"),
        array("name" => "East Caribbean Dollar", "code" => "XCD", "symbol" => "$"),
        array("name" => "Egyptian Pound", "code" => "EGP", "symbol" => "ج.م"),
        array("name" => "Eritrean Nakfa", "code" => "ERN", "symbol" => "Nfk"),
        array("name" => "Estonian Kroon", "code" => "EEK", "symbol" => "kr"),
        array("name" => "Ethiopian Birr", "code" => "ETB", "symbol" => "Nkf"),
        array("name" => "Euro", "code" => "EUR", "symbol" => "€"),
        array("name" => "Falkland Islands Pound", "code" => "FKP", "symbol" => "£"),
        array("name" => "Fijian Dollar", "code" => "FJD", "symbol" => "FJ$"),
        array("name" => "Gambian Dalasi", "code" => "GMD", "symbol" => "D"),
        array("name" => "Georgian Lari", "code" => "GEL", "symbol" => "ლ"),
        array("name" => "German Mark", "code" => "DEM", "symbol" => "DM"),
        array("name" => "Ghanaian Cedi", "code" => "GHS", "symbol" => "GH₵"),
        array("name" => "Gibraltar Pound", "code" => "GIP", "symbol" => "£"),
        array("name" => "Greek Drachma", "code" => "GRD", "symbol" => "₯, Δρχ, Δρ"),
        array("name" => "Guatemalan Quetzal", "code" => "GTQ", "symbol" => "Q"),
        array("name" => "Guinean Franc", "code" => "GNF", "symbol" => "FG"),
        array("name" => "Guyanaese Dollar", "code" => "GYD", "symbol" => "$"),
        array("name" => "Haitian Gourde", "code" => "HTG", "symbol" => "G"),
        array("name" => "Honduran Lempira", "code" => "HNL", "symbol" => "L"),
        array("name" => "Hong Kong Dollar", "code" => "HKD", "symbol" => "$"),
        array("name" => "Hungarian Forint", "code" => "HUF", "symbol" => "Ft"),
        array("name" => "Icelandic Króna", "code" => "ISK", "symbol" => "kr"),
        array("name" => "Indian Rupee", "code" => "INR", "symbol" => "₹"),
        array("name" => "Indonesian Rupiah", "code" => "IDR", "symbol" => "Rp"),
        array("name" => "Iranian Rial", "code" => "IRR", "symbol" => "﷼"),
        array("name" => "Iraqi Dinar", "code" => "IQD", "symbol" => "د.ع"),
        array("name" => "Israeli New Sheqel", "code" => "ILS", "symbol" => "₪"),
        array("name" => "Italian Lira", "code" => "ITL", "symbol" => "L,£"),
        array("name" => "Jamaican Dollar", "code" => "JMD", "symbol" => "J$"),
        array("name" => "Japanese Yen", "code" => "JPY", "symbol" => "¥"),
        array("name" => "Jordanian Dinar", "code" => "JOD", "symbol" => "ا.د"),
        array("name" => "Kazakhstani Tenge", "code" => "KZT", "symbol" => "лв"),
        array("name" => "Kenyan Shilling", "code" => "KES", "symbol" => "KSh"),
        array("name" => "Kuwaiti Dinar", "code" => "KWD", "symbol" => "ك.د"),
        array("name" => "Kyrgystani Som", "code" => "KGS", "symbol" => "лв"),
        array("name" => "Laotian Kip", "code" => "LAK", "symbol" => "₭"),
        array("name" => "Latvian Lats", "code" => "LVL", "symbol" => "Ls"),
        array("name" => "Lebanese Pound", "code" => "LBP", "symbol" => "£"),
        array("name" => "Lesotho Loti", "code" => "LSL", "symbol" => "L"),
        array("name" => "Liberian Dollar", "code" => "LRD", "symbol" => "$"),
        array("name" => "Libyan Dinar", "code" => "LYD", "symbol" => "د.ل"),
        array("name" => "Litecoin", "code" => "LTC", "symbol" => "Ł"),
        array("name" => "Lithuanian Litas", "code" => "LTL", "symbol" => "Lt"),
        array("name" => "Macanese Pataca", "code" => "MOP", "symbol" => "$"),
        array("name" => "Macedonian Denar", "code" => "MKD", "symbol" => "ден"),
        array("name" => "Malagasy Ariary", "code" => "MGA", "symbol" => "Ar"),
        array("name" => "Malawian Kwacha", "code" => "MWK", "symbol" => "MK"),
        array("name" => "Malaysian Ringgit", "code" => "MYR", "symbol" => "RM"),
        array("name" => "Maldivian Rufiyaa", "code" => "MVR", "symbol" => "Rf"),
        array("name" => "Mauritanian Ouguiya", "code" => "MRO", "symbol" => "MRU"),
        array("name" => "Mauritian Rupee", "code" => "MUR", "symbol" => "₨"),
        array("name" => "Mexican Peso", "code" => "MXN", "symbol" => "$"),
        array("name" => "Moldovan Leu", "code" => "MDL", "symbol" => "L"),
        array("name" => "Mongolian Tugrik", "code" => "MNT", "symbol" => "₮"),
        array("name" => "Moroccan Dirham", "code" => "MAD", "symbol" => "MAD"),
        array("name" => "Mozambican Metical", "code" => "MZM", "symbol" => "MT"),
        array("name" => "Myanmar Kyat", "code" => "MMK", "symbol" => "K"),
        array("name" => "Namibian Dollar", "code" => "NAD", "symbol" => "$"),
        array("name" => "Nepalese Rupee", "code" => "NPR", "symbol" => "₨"),
        array("name" => "Netherlands Antillean Guilder", "code" => "ANG", "symbol" => "ƒ"),
        array("name" => "New Taiwan Dollar", "code" => "TWD", "symbol" => "$"),
        array("name" => "New Zealand Dollar", "code" => "NZD", "symbol" => "$"),
        array("name" => "Nicaraguan Córdoba", "code" => "NIO", "symbol" => "C$"),
        array("name" => "Nigerian Naira", "code" => "NGN", "symbol" => "₦"),
        array("name" => "North Korean Won", "code" => "KPW", "symbol" => "₩"),
        array("name" => "Norwegian Krone", "code" => "NOK", "symbol" => "kr"),
        array("name" => "Omani Rial", "code" => "OMR", "symbol" => ".ع.ر"),
        array("name" => "Pakistani Rupee", "code" => "PKR", "symbol" => "₨"),
        array("name" => "Panamanian Balboa", "code" => "PAB", "symbol" => "B/."),
        array("name" => "Papua New Guinean Kina", "code" => "PGK", "symbol" => "K"),
        array("name" => "Paraguayan Guarani", "code" => "PYG", "symbol" => "₲"),
        array("name" => "Peruvian Nuevo Sol", "code" => "PEN", "symbol" => "S/."),
        array("name" => "Philippine Peso", "code" => "PHP", "symbol" => "₱"),
        array("name" => "Polish Zloty", "code" => "PLN", "symbol" => "zł"),
        array("name" => "Qatari Rial", "code" => "QAR", "symbol" => "ق.ر"),
        array("name" => "Romanian Leu", "code" => "RON", "symbol" => "lei"),
        array("name" => "Russian Ruble", "code" => "RUB", "symbol" => "₽"),
        array("name" => "Rwandan Franc", "code" => "RWF", "symbol" => "FRw"),
        array("name" => "Salvadoran Colón", "code" => "SVC", "symbol" => "₡"),
        array("name" => "Samoan Tala", "code" => "WST", "symbol" => "SAT"),
        array("name" => "São Tomé and Príncipe Dobra", "code" => "STD", "symbol" => "Db"),
        array("name" => "Saudi Riyal", "code" => "SAR", "symbol" => "﷼"),
        array("name" => "Serbian Dinar", "code" => "RSD", "symbol" => "din"),
        array("name" => "Seychellois Rupee", "code" => "SCR", "symbol" => "SRe"),
        array("name" => "Sierra Leonean Leone", "code" => "SLL", "symbol" => "Le"),
        array("name" => "Singapore Dollar", "code" => "SGD", "symbol" => "$"),
        array("name" => "Slovak Koruna", "code" => "SKK", "symbol" => "Sk"),
        array("name" => "Solomon Islands Dollar", "code" => "SBD", "symbol" => "Si$"),
        array("name" => "Somali Shilling", "code" => "SOS", "symbol" => "Sh.so."),
        array("name" => "South African Rand", "code" => "ZAR", "symbol" => "R"),
        array("name" => "South Korean Won", "code" => "KRW", "symbol" => "₩"),
        array("name" => "South Sudanese Pound", "code" => "SSP", "symbol" => "£"),
        array("name" => "Special Drawing Rights", "code" => "XDR", "symbol" => "SDR"),
        array("name" => "Sri Lankan Rupee", "code" => "LKR", "symbol" => "Rs"),
        array("name" => "St. Helena Pound", "code" => "SHP", "symbol" => "£"),
        array("name" => "Sudanese Pound", "code" => "SDG", "symbol" => ".س.ج"),
        array("name" => "Surinamese Dollar", "code" => "SRD", "symbol" => "$"),
        array("name" => "Swazi Lilangeni", "code" => "SZL", "symbol" => "E"),
        array("name" => "Swedish Krona", "code" => "SEK", "symbol" => "kr"),
        array("name" => "Swiss Franc", "code" => "CHF", "symbol" => "CHf"),
        array("name" => "Syrian Pound", "code" => "SYP", "symbol" => "LS"),
        array("name" => "Tajikistani Somoni", "code" => "TJS", "symbol" => "SM"),
        array("name" => "Tanzanian Shilling", "code" => "TZS", "symbol" => "TSh"),
        array("name" => "Thai Baht", "code" => "THB", "symbol" => "฿"),
        array("name" => "Tongan Pa'anga", "code" => "TOP", "symbol" => "$"),
        array("name" => "Trinidad & Tobago Dollar", "code" => "TTD", "symbol" => "$"),
        array("name" => "Tunisian Dinar", "code" => "TND", "symbol" => "ت.د"),
        array("name" => "Turkish Lira", "code" => "TRY", "symbol" => "₺"),
        array("name" => "Turkmenistani Manat", "code" => "TMT", "symbol" => "T"),
        array("name" => "Ugandan Shilling", "code" => "UGX", "symbol" => "USh"),
        array("name" => "Ukrainian Hryvnia", "code" => "UAH", "symbol" => "₴"),
        array("name" => "United Arab Emirates Dirham", "code" => "AED", "symbol" => "إ.د"),
        array("name" => "Uruguayan Peso", "code" => "UYU", "symbol" => "$"),
        array("name" => "US Dollar", "code" => "USD", "symbol" => "$"),
        array("name" => "Uzbekistan Som", "code" => "UZS", "symbol" => "лв"),
        array("name" => "Vanuatu Vatu", "code" => "VUV", "symbol" => "VT"),
        array("name" => "Venezuelan BolÃvar", "code" => "VEF", "symbol" => "Bs"),
        array("name" => "Vietnamese Dong", "code" => "VND", "symbol" => "₫"),
        array("name" => "Yemeni Rial", "code" => "YER", "symbol" => "﷼"),
        array("name" => "Zambian Kwacha", "code" => "ZMK", "symbol" => "ZK"),
        array("name" => "Zimbabwean dollar", "code" => "ZWL", "symbol" => "$")
    ),
    'user_status' => [
        'Inactive'  => 0,
        'Active'    => 1,
    ]
];
